name: Open PR Telegram Notify

on:
  pull_request:
    types:
      - reopened
      - opened

jobs:
  notify_pr_open:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify new pr on telegram group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_KEY }}
          disable_web_page_preview: true
          message: |
            ${{ github.actor }} ha creato una pull request per migliorare il gruppo.
            Tramite il repository open source, puoi amministrare il gruppo democraticamente, decidere le regole, gli amministratori e il futuro del gruppo.
            Partecipa, vota e decidi: ${{ github.event.pull_request.html_url }}
