name: Open Issue Telegram Notify

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify new issue on telegram group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_KEY }}
          disable_web_page_preview: true
          format: markdown
          message: |
            ${{ github.actor }} ha creato una nuova issue: [${{github.event.issue.title}}](${{ github.event.issue.html_url }})\\.
            Tramite il repository open source, puoi partecipare ad amministrare il gruppo democraticamente, decidere le regole, gli amministratori e il futuro del gruppo\\.
            Partecipa, vota e decidi: https://github\\.com/${{ github.repository }}\\.
